.\" generated with Ronn/v0.5
.\" http://github.com/rtomayko/ronn/
.
.TH "SHOE" "3" "October 2010" "Matthew Todd" "RubyGems Manual"
.
.SH "NAME"
\fBshoe\fR \-\- standard Rake tasks for your RubyGems project
.
.SH "SYNOPSIS"
require 'shoe'
.
.br
Shoe.install_tasks
.
.SH "DESCRIPTION"
\fBShoe.install_tasks\fR defines a number of standard \fBrake(1)\fR tasks for your
RubyGems project. These tasks derive their configuration from your
Gem::Specification, and they assume you are using \fBgit(1)\fR.
.
.SH "TASKS"
.
.TP
\fBrake clean\fR
Remove ignored files. Calls something like \fBgit\-clean(1)\fR with the \fB\-fdX\fR
options, honoring your \fBgitignore(5)\fR rules, but preserving \fB.bundle/\fR.
.
.TP
\fBrake compile\fR
Compile C extensions with RubyGems' built\-in Gem::Ext::ExtConfBuilder,
reading the \fBextensions\fR field in your Gem::Specification.
.
.TP
\fBrake cucumber\fR
Run Cucumber features, using the \fBdefault\fR profile in \fBcucumber.yml\fR.
Tasks for the other profiles are placed under the cucumber namespace, so you
could run a hypothetical \fBwip\fR profile with \fBrake cucumber:wip\fR, etc.
.
.TP
\fBrake rdoc\fR
Generate RDoc documentation with RubyGems' built\-in Gem::DocManager, which
reads the \fBrdoc_options\fR and \fBextra_rdoc_files\fR fields in your
Gem::Specification.
.
.TP
\fBrake ronn\fR
Generate man pages with \fBronn(1)\fR from the \fBman/*.ronn\fR sources listed in the \fBfiles\fR field of your Gem::Specification. (The generated manpages will then
be available via \fBgem\-man(1)\fR once your gem is installed.)
.
.TP
\fBrake test\fR
Run tests with RubyGems' built\-in Gem::Validator, which reads the \fBtest_files\fR field in your Gem::Specification to know which tests to run.
.
.P
Note these tasks check conditions before defining themselves, so that your \fBrake \-\-tasks\fR list stays relevant and compact. You won't see all the tasks all
the time.
.
.SH "AUTHOR"
Matthew Todd, \fImatthewtodd\fR on GitHub. Do drop
me a line if you use \fBshoe\fR \-\- I'd love to hear from you!
.
.SH "SEE ALSO"
\fIhttp://docs.rubygems.org/read/chapter/20\fR
